name = "my-photo-album"
main = "src/index.js"
compatibility_date = "2023-12-01"

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "album"

[[kv_namespaces]]
binding = "PHOTO_METADATA"
id = "951622a24c8b411f9ec8e9de85270e84"

#[vars]
#ADMIN_PASSWORD = "your_new_password"